const projects = [
    // ==========================================
    // 1. BTS (Behind The Scenes) - [Total: 8]
    // ==========================================
    { name: "BTS Video 1", eventType: "bts", src: "https://www.youtube.com/embed/YnG5jPu9Bsg", where: "youtube" },
    { name: "BTS Video 2", eventType: "bts", src: "https://www.youtube.com/embed/hSx_lEMpD8Q", where: "youtube" },
    { name: "Decode BTS Reel 1", eventType: "bts", src: "https://www.instagram.com/reel/DOVu5i3D5rW/embed/", where: "instagram" },
    { name: "Decode BTS Reel 2", eventType: "bts", src: "https://www.instagram.com/reel/DOXq4myiO9s/embed/", where: "instagram" },
    { name: "Decode BTS Reel 3", eventType: "bts", src: "https://www.instagram.com/reel/DRgvAUvFEaJ/embed/", where: "instagram" },
    { name: "Decode BTS Reel 4", eventType: "bts", src: "https://www.instagram.com/reel/DOntYmRgd8g/embed/", where: "instagram" },
    { name: "Mahabelly BTS", eventType: "bts", src: "https://www.instagram.com/reel/DOvUE3Zj5s2/embed/", where: "instagram" },
    { name: "Yati BTS", eventType: "bts", src: "https://www.instagram.com/reel/DPMTTXCD84Y/embed/", where: "instagram" },

    // ==========================================
    // 2. F&B (Food & Beverage) - [Total: 35]
    // ==========================================
    { name: "F&B YT 1", eventType: "F&B", src: "https://www.youtube.com/embed/YnG5jPu9Bsg", where: "youtube" },
    { name: "F&B YT 2", eventType: "F&B", src: "https://www.youtube.com/embed/4NK6_zssse8", where: "youtube" },
    { name: "F&B YT 3", eventType: "F&B", src: "https://www.youtube.com/embed/1r0cuPoCkso", where: "youtube" },
    { name: "F&B YT 4", eventType: "F&B", src: "https://www.youtube.com/embed/87UWJkYME50", where: "youtube" },
    { name: "F&B YT 5", eventType: "F&B", src: "https://www.youtube.com/embed/xMkUmU6qasI", where: "youtube" },
    { name: "F&B YT 6", eventType: "F&B", src: "https://www.youtube.com/embed/1TS-h0-EgsQ", where: "youtube" },
    
    { name: "Anardana (Aug)", eventType: "F&B", src: "https://www.instagram.com/p/DNh_iP1PG3q/embed/", where: "instagram" },
    { name: "Bira 91", eventType: "F&B", src: "https://www.instagram.com/reel/DNnY5xkPdzm/embed/", where: "instagram" },
    { name: "Cafe Delhi Heights", eventType: "F&B", src: "https://www.instagram.com/reel/DNSyftWP3G9/embed/", where: "instagram" },
    { name: "Gola Sizzler's", eventType: "F&B", src: "https://www.instagram.com/reel/DNN2QuRvUxV/embed/", where: "instagram" },
    { name: "Laidback Cafe", eventType: "F&B", src: "https://www.instagram.com/reel/DNag6JsNIni/embed/", where: "instagram" },
    { name: "Mahabelly (Aug)", eventType: "F&B", src: "https://www.instagram.com/reel/DN-j62zD_Ee/embed/", where: "instagram" },
    { name: "Perch", eventType: "F&B", src: "https://www.instagram.com/reel/DN8FW1hj4nB/embed/", where: "instagram" },
    { name: "Flow", eventType: "F&B", src: "https://www.instagram.com/reel/DOOMVDFDwWV/embed/", where: "instagram" },
    { name: "Got Tea", eventType: "F&B", src: "https://www.instagram.com/reel/DRT_po_j6m7/embed/", where: "instagram" },
    { name: "Mahabally (Sep)", eventType: "F&B", src: "https://www.instagram.com/reel/DQW0vz3D__y/embed/", where: "instagram" },
    { name: "Nonnas", eventType: "F&B", src: "https://www.instagram.com/reel/DOiiCJLjZdp/embed/", where: "instagram" },
    { name: "Tablespoon 1", eventType: "F&B", src: "https://www.instagram.com/reel/DOn7Vl9D7gg/embed/", where: "instagram" },
    { name: "Tablespoon 2", eventType: "F&B", src: "https://www.instagram.com/reel/DOS15JMj6IS/embed/", where: "instagram" },
    { name: "Viteanom", eventType: "F&B", src: "https://www.instagram.com/reel/DP1Z9D_jzP3/embed/", where: "instagram" },
    { name: "F&B Combined 1", eventType: "F&B", src: "https://www.instagram.com/reel/DRwTsdCCBdn/embed/", where: "instagram" },
    { name: "F&B Combined 2", eventType: "F&B", src: "https://www.instagram.com/reel/DRzTgUTASby/embed/", where: "instagram" },
    { name: "F&B Combined 3", eventType: "F&B", src: "https://www.instagram.com/reel/DSF5dT0FGr2/embed/", where: "instagram" },
    { name: "F&B Combined 4", eventType: "F&B", src: "https://www.instagram.com/reel/DSFIJuoDSsf/embed/", where: "instagram" },
    { name: "F&B Combined 5", eventType: "F&B", src: "https://www.instagram.com/reel/DSzC3HQAW1a/embed/", where: "instagram" },
    { name: "F&B Combined 6", eventType: "F&B", src: "https://www.instagram.com/reel/DS9bFbrgY9p/embed/", where: "instagram" },
    { name: "F&B Combined 7", eventType: "F&B", src: "https://www.instagram.com/reel/DS__8a7gUBr/embed/", where: "instagram" },
    { name: "F&B Combined 8", eventType: "F&B", src: "https://www.instagram.com/reel/DTDHDSmAYNz/embed/", where: "instagram" },
    { name: "F&B Combined 9", eventType: "F&B", src: "https://www.instagram.com/reel/DUNef4Kgckz/embed/", where: "instagram" },
    { name: "F&B Combined 10", eventType: "F&B", src: "https://www.instagram.com/reel/DUVoDSngTfm/embed/", where: "instagram" },
    { name: "Bira (Dlf Avenue)", eventType: "F&B", src: "https://www.instagram.com/reel/DS2fT-KDx1h/embed/", where: "instagram" },
    { name: "Prech (Dlf Avenue)", eventType: "F&B", src: "https://www.instagram.com/reel/DSNIFSfD0it/embed/", where: "instagram" },
    { name: "Vietnam (Dlf Avenue)", eventType: "F&B", src: "https://www.instagram.com/reel/DSSRGA7D5CH/embed/", where: "instagram" },
    { name: "F&B Avenue Combined 1", eventType: "F&B", src: "https://www.instagram.com/reel/DSxU2OOj2OL/embed/", where: "instagram" },
    { name: "F&B Avenue Combined 2", eventType: "F&B", src: "https://www.instagram.com/reel/DSus-_Bj8iB/embed/", where: "instagram" },
    { name: "F&B Avenue Combined 3", eventType: "F&B", src: "https://www.instagram.com/reel/DSmLqSTj6iT/embed/", where: "instagram" },

    // ==========================================
    // 3. Interior - [Total: 24]
    // ==========================================
    { name: "Interior Reel 1", eventType: "Interior", src: "https://www.instagram.com/reel/DNZ-z-NPSHC/embed/", where: "instagram" },
    { name: "Interior YT 1", eventType: "Interior", src: "https://www.youtube.com/embed/IIljt9bOc7s", where: "youtube" },
    { name: "Interior Reel 2", eventType: "Interior", src: "https://www.instagram.com/reel/DMsY-uGB-sA/embed/", where: "instagram" },
    { name: "Interior Reel 3", eventType: "Interior", src: "https://www.instagram.com/reel/DN3GHE2QvZj/embed/", where: "instagram" },
    { name: "Interior Reel 4", eventType: "Interior", src: "https://www.instagram.com/reel/DNantSFhFix/embed/", where: "instagram" },
    { name: "Interior Reel 5", eventType: "Interior", src: "https://www.instagram.com/reel/DUS8HDzjwrZ/embed/", where: "instagram" },
    { name: "Interior Reel 6", eventType: "Interior", src: "https://www.instagram.com/reel/DTqtsN5E43U/embed/", where: "instagram" },
    { name: "Interior Reel 7", eventType: "Interior", src: "https://www.instagram.com/reel/DTmxxgND4cp/embed/", where: "instagram" },
    { name: "Interior Reel 8", eventType: "Interior", src: "https://www.instagram.com/reel/DTXSFARj31H/embed/", where: "instagram" },
    { name: "Interior Reel 9", eventType: "Interior", src: "https://www.instagram.com/reel/DThrAaLD1kh/embed/", where: "instagram" },
    { name: "Interior Reel 10", eventType: "Interior", src: "https://www.instagram.com/reel/DVGg1lGDzq-/embed/", where: "instagram" },
    { name: "Interior Reel 11", eventType: "Interior", src: "https://www.instagram.com/reel/DVJGVVCj_T8/embed/", where: "instagram" },
    { name: "Interior Reel 12", eventType: "Interior", src: "https://www.instagram.com/reel/DVDax4ED6vt/embed/", where: "instagram" },
    { name: "Interior Reel 13", eventType: "Interior", src: "https://www.instagram.com/reel/DVBAlOTj2L7/embed/", where: "instagram" },
    { name: "Interior Reel 14", eventType: "Interior", src: "https://www.instagram.com/reel/DTPUCoQj5h7/embed/", where: "instagram" },
    { name: "Interior Reel 15", eventType: "Interior", src: "https://www.instagram.com/reel/DTIch52j5ID/embed/", where: "instagram" },
    { name: "Interior Reel 16", eventType: "Interior", src: "https://www.instagram.com/reel/DRzR6ifj1CH/embed/", where: "instagram" },
    { name: "Interior Reel 17", eventType: "Interior", src: "https://www.instagram.com/reel/DQ_60Raj9dp/embed/", where: "instagram" },
    { name: "Interior Reel 18", eventType: "Interior", src: "https://www.instagram.com/reel/DVa9O6pgWCG/embed/", where: "instagram" },
    { name: "Interior Reel 19", eventType: "Interior", src: "https://www.instagram.com/reel/DV_BY1gCsgy/embed/", where: "instagram" },
    { name: "Interior Reel 20", eventType: "Interior", src: "https://www.instagram.com/reel/DUFwwWWjzMD/embed/", where: "instagram" },
    { name: "Interior Reel 21", eventType: "Interior", src: "https://www.instagram.com/reel/DTsYHICj71C/embed/", where: "instagram" },
    { name: "Interior Reel 22", eventType: "Interior", src: "https://www.instagram.com/reel/DR4n5cwj3JU/embed/", where: "instagram" },
    { name: "Interior Reel 23", eventType: "Interior", src: "https://www.instagram.com/reel/DOd1r55D5we/embed/", where: "instagram" },

    // ==========================================
    // 4. Lifestyle - [Total: 36]
    // ==========================================
    { name: "Lifestyle YT 1", eventType: "Lifestyle", src: "https://www.youtube.com/embed/hSx_lEMpD8Q", where: "youtube" },
    { name: "Lifestyle YT 2", eventType: "Lifestyle", src: "https://www.youtube.com/embed/yJkbARhBBg8", where: "youtube" },
    { name: "Lifestyle YT 3", eventType: "Lifestyle", src: "https://www.youtube.com/embed/fBJcIB6n8og", where: "youtube" },
    { name: "Lifestyle YT 4", eventType: "Lifestyle", src: "https://www.youtube.com/embed/AlKTHZXGrwc", where: "youtube" },
    { name: "Lifestyle YT 5", eventType: "Lifestyle", src: "https://www.youtube.com/embed/Uam8_tFa4HQ", where: "youtube" },
    { name: "Lifestyle YT 6", eventType: "Lifestyle", src: "https://www.youtube.com/embed/mjvhGiNGjlo", where: "youtube" },
    { name: "Lifestyle YT 7", eventType: "Lifestyle", src: "https://www.youtube.com/embed/Bq3JXfer57Q", where: "youtube" },
    { name: "Lifestyle YT 8", eventType: "Lifestyle", src: "https://www.youtube.com/embed/jfSFjguFitw", where: "youtube" },
    { name: "Lifestyle Reel 1", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DUvNJQCAT5L/embed/", where: "instagram" },
    { name: "Lifestyle Reel 2", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DP8yRsPAeeL/embed/", where: "instagram" },
    { name: "Lifestyle Reel 3", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DPeMIQ8j5zu/embed/", where: "instagram" },
    { name: "Lifestyle Reel 4", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DPG1fR8DsFi/embed/", where: "instagram" },
    { name: "Lifestyle Reel 5", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DLFI4jNBkys/embed/", where: "instagram" },
    { name: "Lifestyle Reel 6", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DPg49vAjxmT/embed/", where: "instagram" },
    { name: "Lifestyle Reel 7", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DPlrmLfjyIb/embed/", where: "instagram" },
    { name: "Lifestyle Reel 8", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DQV1vWYjJGW/embed/", where: "instagram" },
    { name: "Lifestyle Reel 9", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DUnbMuYgYFT/embed/", where: "instagram" },
    { name: "Lifestyle Reel 10", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DPWVBi6ijsK/embed/", where: "instagram" },
    { name: "Lifestyle Reel 11", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DOtCbb_FbN0/embed/", where: "instagram" },
    { name: "Lifestyle Reel 12", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DOntYmRgd8g/embed/", where: "instagram" },
    { name: "Lifestyle Reel 13", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DOc-kNPkTL_/embed/", where: "instagram" },
    { name: "Lifestyle Reel 14", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DP3v0WUj0Jv/embed/", where: "instagram" },
    { name: "Lifestyle Reel 15", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DPMNq-_kY0I/embed/", where: "instagram" },
    { name: "Lifestyle Reel 16", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DQ1MU4TD1it/embed/", where: "instagram" },
    { name: "Lifestyle Reel 17", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DOVu5i3D5rW/embed/", where: "instagram" },
    { name: "Lifestyle Reel 18", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DLjU2yghCJq/embed/", where: "instagram" },
    { name: "Lifestyle Reel 19", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DVgcFvKD_eV/embed/", where: "instagram" },
    { name: "Lifestyle Reel 20", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DOn-57djxqd/embed/", where: "instagram" },
    { name: "Lifestyle Reel 21", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DUX82jwjzi4/embed/", where: "instagram" },
    { name: "Lifestyle Reel 22", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DU0tBDeDwBV/embed/", where: "instagram" },
    { name: "Lifestyle Reel 23", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DPjbZ8Tj7P2/embed/", where: "instagram" },
    { name: "Lifestyle Reel 24", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DJrXxtEvi69/embed/", where: "instagram" },
    { name: "Lifestyle Reel 25", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DUsWhYggf0J/embed/", where: "instagram" },
    { name: "Lifestyle Reel 26", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DQ4LviDCsu5/embed/", where: "instagram" },
    { name: "Lifestyle Reel 27", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DPwUaECjYTC/embed/", where: "instagram" },
    { name: "Lifestyle Reel 28", eventType: "Lifestyle", src: "https://www.instagram.com/reel/DO_JvR5EQLs/embed/", where: "instagram" },

    // ==========================================
    // 5. Events - [Total: 18]
    // ==========================================
    { name: "Events YT 1", eventType: "Events", src: "https://www.youtube.com/embed/qUKJfeEQlbM", where: "youtube" },
    { name: "Event Reel 1", eventType: "Events", src: "https://www.instagram.com/reel/DT-M6_gE67o/embed/", where: "instagram" },
    { name: "Events YT 2", eventType: "Events", src: "https://www.youtube.com/embed/hghM5zhXuv0", where: "youtube" },
    { name: "Event Reel 2", eventType: "Events", src: "https://www.instagram.com/reel/DJ3JcSFvf_-/embed/", where: "instagram" },
    { name: "Event Reel 3", eventType: "Events", src: "https://www.instagram.com/reel/DOnUxqIjesJ/embed/", where: "instagram" },
    { name: "Event Reel 4", eventType: "Events", src: "https://www.instagram.com/reel/DO8HXEcDV-b/embed/", where: "instagram" },
    { name: "Event Reel 5", eventType: "Events", src: "https://www.instagram.com/reel/DOxq2DiDy5n/embed/", where: "instagram" },
    { name: "Event Reel 6", eventType: "Events", src: "https://www.instagram.com/reel/DPOpED6E12x/embed/", where: "instagram" },
    { name: "Event Reel 7", eventType: "Events", src: "https://www.instagram.com/reel/DS2P9Rzk9pv/embed/", where: "instagram" },
    { name: "Event Reel 8", eventType: "Events", src: "https://www.instagram.com/reel/DSmqrZLAfD-/embed/", where: "instagram" },
    { name: "Event Reel 9", eventType: "Events", src: "https://www.instagram.com/reel/DM-j5FbtxA7/embed/", where: "instagram" },
    { name: "Event Reel 10", eventType: "Events", src: "https://www.instagram.com/reel/DS4SknrCTq9/embed/", where: "instagram" },
    { name: "Event Reel 11", eventType: "Events", src: "https://www.instagram.com/reel/DQWQKAMFT8n/embed/", where: "instagram" },
    { name: "Event Reel 12", eventType: "Events", src: "https://www.instagram.com/reel/DJdzg0kpKpG/embed/", where: "instagram" },
    { name: "Event Reel 13", eventType: "Events", src: "https://www.instagram.com/reel/DLUYj1tTGkT/embed/", where: "instagram" },
    { name: "Events YT 3", eventType: "Events", src: "https://www.youtube.com/embed/BUVWXyEMKPY", where: "youtube" },
    { name: "Events YT 4", eventType: "Events", src: "https://www.youtube.com/embed/FLUnYEK_yFU", where: "youtube" },
    { name: "Event Reel 14", eventType: "Events", src: "https://www.instagram.com/reel/DWgpbdFk25W/embed/", where: "instagram" },

    // ==========================================
    // 6. Podcast-Interview - [Total: 11]
    // ==========================================
    { name: "Podcast Reel 1", eventType: "Podcast-Interview", src: "https://www.instagram.com/reel/DQ_60Raj9dp/embed/", where: "instagram" },
    { name: "Podcast Reel 2", eventType: "Podcast-Interview", src: "https://www.instagram.com/reel/DQg4OItD6BV/embed/", where: "instagram" },
    { name: "Podcast Reel 3", eventType: "Podcast-Interview", src: "https://www.instagram.com/reel/DP1Z9D_jzP3/embed/", where: "instagram" },
    { name: "Podcast Reel 4", eventType: "Podcast-Interview", src: "https://www.instagram.com/reel/DPlRV1aj2km/embed/", where: "instagram" },
    { name: "Podcast Reel 5", eventType: "Podcast-Interview", src: "https://www.instagram.com/reel/DPY5iKLD3Mk/embed/", where: "instagram" },
    { name: "Podcast Reel 6", eventType: "Podcast-Interview", src: "https://www.instagram.com/reel/DPMTTXCD84Y/embed/", where: "instagram" },
    { name: "Podcast Reel 7", eventType: "Podcast-Interview", src: "https://www.instagram.com/reel/DO-lU0sjz34/embed/", where: "instagram" },
    { name: "Podcast Reel 8", eventType: "Podcast-Interview", src: "https://www.instagram.com/reel/DOvUE3Zj5s2/embed/", where: "instagram" },
    { name: "Podcast YT 1", eventType: "Podcast-Interview", src: "https://www.youtube.com/embed/tiA36bOABvA", where: "youtube" },
    { name: "Podcast YT 2", eventType: "Podcast-Interview", src: "https://www.youtube.com/embed/_wth1iC7s7E", where: "youtube" },
    { name: "Podcast YT 3", eventType: "Podcast-Interview", src: "https://www.youtube.com/embed/qok7Ypv9SiI", where: "youtube" },

    // ==========================================
    // 7. CSPOC - [Total: 6]
    // ==========================================
    { name: "CSPOC Video 1 (Insta)", eventType: "CSPOC", src: "https://www.instagram.com/reel/DTmcbD3Eboa/embed/", where: "instagram" },
    { name: "CSPOC Video 1 (YT)", eventType: "CSPOC", src: "https://www.youtube.com/embed/T4G5bXvzGYI", where: "youtube" },
    { name: "CSPOC Video 2 (YT)", eventType: "CSPOC", src: "https://www.youtube.com/embed/36NO045jD6Q", where: "youtube" },
    { name: "CSPOC Video 3", eventType: "CSPOC", src: "https://www.instagram.com/reel/DUGbEBCj_ky/embed/", where: "instagram" },
    { name: "CSPOC Video 4", eventType: "CSPOC", src: "https://www.instagram.com/reel/DTzfYfdkako/embed/", where: "instagram" },
    { name: "CSPOC Video 5", eventType: "CSPOC", src: "https://www.instagram.com/reel/DTdkCNHkhtH/embed/", where: "instagram" },
]